# Generated by Django 2.1.5 on 2019-07-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('Name', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
