# Generated by Django 2.1.5 on 2019-07-27 08:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
