# Generated by Django 2.1.5 on 2019-07-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190727_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='link',
            new_name='video',
        ),
    ]
