# Generated by Django 2.1.5 on 2019-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190727_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
