# Generated by Django 2.1.5 on 2019-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='Description',
            new_name='Description1',
        ),
        migrations.AddField(
            model_name='videos',
            name='Description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='Description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='Thumbnail',
            field=models.ImageField(null=True, upload_to='upload_images/'),
        ),
    ]
