# Generated by Django 2.1.5 on 2019-09-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_audiofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
