# Generated by Django 2.1.5 on 2019-11-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Class', models.CharField(max_length=35)),
                ('Subjects', models.CharField(max_length=35)),
                ('Contact_no', models.CharField(max_length=12, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Class', models.CharField(max_length=35)),
                ('Subjects', models.CharField(max_length=35)),
                ('Contact_no', models.CharField(max_length=12, unique=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
