# Generated by Django 2.1.7 on 2020-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('College', models.CharField(max_length=35)),
                ('header_pic', models.ImageField(upload_to='upload_images/')),
                ('profile_pic', models.ImageField(upload_to='upload_images/')),
                ('Course1', models.CharField(max_length=35)),
                ('Course2', models.CharField(max_length=35, null=True)),
                ('Course3', models.CharField(max_length=35, null=True)),
                ('Course4', models.CharField(max_length=35, null=True)),
                ('Course5', models.CharField(max_length=35, null=True)),
                ('Speciality', models.CharField(max_length=35, null=True)),
                ('job', models.CharField(max_length=35, null=True)),
                ('Contact_no', models.CharField(max_length=12, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Live_class',
        ),
        migrations.DeleteModel(
            name='Tutions',
        ),
    ]
