# Generated by Django 2.1.7 on 2020-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_auto_20200104_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='insta',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='twitter',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
