# Generated by Django 2.1.5 on 2019-08-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('first_para', models.TextField(max_length=1000, null=True)),
                ('Second_para', models.TextField(max_length=1000, null=True)),
                ('Image_1', models.ImageField(upload_to='static/upload_images/')),
                ('Third_para', models.TextField(max_length=1000, null=True)),
                ('Image_2', models.ImageField(upload_to='static/upload_images/')),
                ('Fourth_para', models.TextField(blank=True, max_length=1000, null=True)),
                ('Image_3', models.ImageField(upload_to='static/upload_images/')),
                ('Fifth_para', models.TextField(blank=True, max_length=1000, null=True)),
                ('Sixth_para', models.TextField(blank=True, max_length=1000, null=True)),
                ('pub_date', models.DateTimeField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35)),
                ('Message', models.TextField(null=True)),
                ('Email', models.CharField(blank=True, max_length=55, null=True)),
                ('Website', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
