# Generated by Django 2.1.5 on 2019-08-08 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_auto_20190808_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Fifth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Fourth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Header_pic',
            field=models.ImageField(null=True, upload_to='static/upload_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_1',
            field=models.ImageField(null=True, upload_to='static/upload_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_2',
            field=models.ImageField(null=True, upload_to='static/upload_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_3',
            field=models.ImageField(null=True, upload_to='static/upload_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Sixth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Third_para',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='first_para',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
