# Generated by Django 2.1.5 on 2019-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190809_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_para',
            field=models.TextField(null=True),
        ),
    ]
