# Generated by Django 2.1.5 on 2019-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20190809_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Third_para',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
