# Generated by Django 2.1.5 on 2019-08-10 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0010_auto_20190810_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Fifth_para',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Fourth_para',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_1',
            field=models.ImageField(default=1, upload_to='static/upload_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_2',
            field=models.ImageField(default=1, upload_to='static/upload_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Image_3',
            field=models.ImageField(default=1, upload_to='static/upload_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Sixth_para',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Third_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='first_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
