# Generated by Django 2.1.5 on 2019-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20190810_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Header_pic',
            field=models.ImageField(upload_to='media/static/upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_1',
            field=models.ImageField(upload_to='media/static/upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_2',
            field=models.ImageField(upload_to='media/static/upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_3',
            field=models.ImageField(upload_to='media/static/upload_images/'),
        ),
    ]
