# Generated by Django 2.1.5 on 2019-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20190811_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Header_pic',
            field=models.ImageField(upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_1',
            field=models.ImageField(upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_2',
            field=models.ImageField(upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_3',
            field=models.ImageField(upload_to='upload_images/'),
        ),
    ]
