# Generated by Django 2.1.5 on 2019-08-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_auto_20190811_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Fifth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Fourth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sixth_para',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Third_para',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_para',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
