# Generated by Django 2.1.5 on 2019-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_comment_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Fifth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Fourth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Header_pic',
            field=models.ImageField(null=True, upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_1',
            field=models.ImageField(null=True, upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_2',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image_3',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Second_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Sixth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Third_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Email',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='Website',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
