# Generated by Django 2.1.5 on 2019-08-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_comment_com_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogs',
        ),
    ]
