# Generated by Django 2.1.5 on 2019-08-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_remove_comment_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
