# Generated by Django 2.1.5 on 2019-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=24)),
            ],
        ),
    ]
