# Generated by Django 2.1.5 on 2019-12-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_ashish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ashish',
        ),
    ]
