# Generated by Django 2.1.5 on 2019-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_auto_20191227_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='events',
            field=models.BooleanField(default=False),
        ),
    ]
