# Generated by Django 2.1.5 on 2019-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_blog_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Counselling',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='acadmics',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='events',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mfitness',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='opportunites',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='self_dev',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tech_skills',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_manag',
            field=models.BooleanField(),
        ),
    ]
