# Generated by Django 2.1.7 on 2020-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_auto_20191228_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Counselling',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='acadmics',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='events',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mfitness',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='opportunites',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='self_dev',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tech_skills',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time_manag',
            field=models.BooleanField(),
        ),
    ]
