# Generated by Django 2.1.7 on 2020-01-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0028_auto_20200103_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
