# Generated by Django 2.1.5 on 2019-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('audio_file', models.FileField(upload_to='music')),
                ('cover', models.ImageField(upload_to='upload_images/')),
                ('speaker', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
