# Generated by Django 2.1.5 on 2019-09-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='Profile_images/')),
                ('Description', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField()),
                ('insta', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Writer'),
        ),
    ]
