# Generated by Django 2.1.5 on 2019-09-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20190903_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episodes_name', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=150)),
                ('audio_file', models.FileField(upload_to='music')),
                ('cover', models.ImageField(upload_to='upload_images/')),
                ('pub_date', models.DateTimeField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Writer')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='Episodes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode'),
            preserve_default=False,
        ),
    ]
