# Generated by Django 2.1.7 on 2020-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20200105_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
